# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd ./frontpage
          npm install
      - name: Build
        run: |
          cd ./frontpage  
          npm run build
      - name: Combine projects
        run: |
          mkdir hosted
          cp -r ./frontpage/build ./hosted
          echo Frontpage was copied
          mkdir hosted/recipe
          cp -r ./recipe ./hosted/recipe
          echo Recipe was copied
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: hosted

  # This job will upload the commited dist-folder to firebase hosting
  deploy:
    name: Deploy
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: hosted
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:${{ secrets.WEB_HOST }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
