# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job will upload the commited dist-folder to firebase hosting
  firebase-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - name: build frontpage
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
          # start by preventing error: dir hosted does not exist and then build frontpage, then copy all projects to their path
          run: |
            mkdir hosted
            rm -R ./hosted/
            mkdir hosted
            cd ./frontpage/
            npm install
            npm run build
            cd ..
            cp -r ./frontpage/build ./hosted
      - name: prepare upload directory
        run: |
          mkdir hosted/recipe
          cp -r ./recipe ./hosted/recipe
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web-dgrendev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
